global:
  imagePullSecrets: []
 #   - name: my-registry-secret
accessManager:
  manager:
    args:
    - --diagnostics-address=:8443
    - --v=5
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: docker.io/projectsveltos/access-manager
      tag: v0.45.0
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
addonController:
  controller:
    args:
    - --diagnostics-address=:8443
    - --report-mode=0
    - --shard-key=
    - --v=5
    - --version=v0.45.0
    argsAgentMgmtCluster:
    - --diagnostics-address=:8443
    - --report-mode=0
    - --agent-in-mgmt-cluster
    - --shard-key=
    - --v=5
    - --version=v0.45.0
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      seccompProfile:
        type: RuntimeDefault
    image:
      repository: docker.io/projectsveltos/addon-controller
      tag: v0.45.0
    resources:
      requests:
        memory: 256Mi
    extraEnv: []
  ports:
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: 8443
  nodeSelector: {}
  replicas: 1
  tolerations: []
  type: ClusterIP
classifierManager:
  manager:
    args:
    - --diagnostics-address=:8443
    - --report-mode=0
    - --shard-key=
    - --v=5
    - --version=v0.45.0
    argsAgentMgmtCluster:
    - --diagnostics-address=:8443
    - --report-mode=0
    - --agent-in-mgmt-cluster
    - --shard-key=
    - --v=5
    - --version=v0.45.0
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: docker.io/projectsveltos/classifier
      tag: v0.45.0
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
conversionWebhook:
  replicas: 1
  sveltosWebhook:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: docker.io/projectsveltos/webhook-conversion
      tag: v0.45.0
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
eventManager:
  manager:
    args:
    - --diagnostics-address=:8443
    - --shard-key=
    - --v=5
    - --version=v0.45.0
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: docker.io/projectsveltos/event-manager
      tag: v0.45.0
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
hcManager:
  manager:
    args:
    - --diagnostics-address=:8443
    - --shard-key=
    - --v=5
    - --version=v0.45.0
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: docker.io/projectsveltos/healthcheck-manager
      tag: v0.45.0
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
kubernetesClusterDomain: cluster.local
registerMgmtClusterJob:
  enabled: true
  backoffLimit: 4
  registerMgmtCluster:
    args:
    - --labels=
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: docker.io/projectsveltos/register-mgmt-cluster
      tag: v0.45.0
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: 128Mi
scManager:
  manager:
    args:
    - --diagnostics-address=:8443
    - --shard-key=
    - --v=5
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: docker.io/projectsveltos/sveltoscluster-manager
      tag: v0.45.0
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  ports:
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: 8443
  replicas: 1
  tolerations: []
  type: ClusterIP
shardController:
  manager:
    args:
    - --diagnostics-address=:8443
    - --v=5
    - --report-mode=0
    argsAgentMgmtCluster:
    - --diagnostics-address=:8443
    - --report-mode=0
    - --agent-in-mgmt-cluster
    - --v=5
    extraEnv: []
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: docker.io/projectsveltos/shard-controller
      tag: v0.45.0
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 128Mi
  nodeSelector: {}
  replicas: 1
  tolerations: []
prometheus:
  enabled: false
agent:
  managementCluster: false
telemetry:
  disabled: false
webhookService:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  type: ClusterIP
webhook:
  conversion: false
